version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  loopback: # name of second service
    depends_on:
      - mysql
    container_name: esalocal
    restart: always
    build: .
    ports:
      - '3000:3000' # specify port mapping
    links:
      - mysql # link this service to the database service
  mysql: # name of first service
    container_name: mysql
    image: mysql:latest # specify the image to build container from
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
